# 张量

In [1]:
from __future__ import print_function

In [2]:
import torch
x=torch.Tensor(5,3)
x=torch.rand(5,3)
x
x.size()

tensor([[0.6816, 0.2698, 0.2950],
        [0.4154, 0.5099, 0.4129],
        [0.3006, 0.9119, 0.4654],
        [0.5953, 0.5823, 0.7199],
        [0.9771, 0.0329, 0.5298]])

torch.Size([5, 3])

In [3]:
y=torch.rand(5,3)
x+y
torch.add(x,y)

tensor([[0.7284, 0.5219, 0.3770],
        [0.7152, 0.9879, 0.5918],
        [0.3451, 0.9718, 0.8475],
        [0.6886, 1.0477, 0.8579],
        [1.9615, 0.3486, 0.7582]])

tensor([[0.7284, 0.5219, 0.3770],
        [0.7152, 0.9879, 0.5918],
        [0.3451, 0.9718, 0.8475],
        [0.6886, 1.0477, 0.8579],
        [1.9615, 0.3486, 0.7582]])

In [5]:
result=torch.Tensor(5,3)
torch.add(x,y,out=result)
y.add_(x)

tensor([[0.7284, 0.5219, 0.3770],
        [0.7152, 0.9879, 0.5918],
        [0.3451, 0.9718, 0.8475],
        [0.6886, 1.0477, 0.8579],
        [1.9615, 0.3486, 0.7582]])

tensor([[0.7284, 0.5219, 0.3770],
        [0.7152, 0.9879, 0.5918],
        [0.3451, 0.9718, 0.8475],
        [0.6886, 1.0477, 0.8579],
        [1.9615, 0.3486, 0.7582]])

In [7]:
x[:,1]

tensor([0.2698, 0.5099, 0.9119, 0.5823, 0.0329])

# Numpy桥

In [10]:
a=torch.ones(5)
b=a.numpy()
a
b
b[0]=0
a
b

tensor([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.], dtype=float32)

tensor([0., 1., 1., 1., 1.])

array([0., 1., 1., 1., 1.], dtype=float32)

In [11]:
a.add_(1)
a
b

tensor([1., 2., 2., 2., 2.])

tensor([1., 2., 2., 2., 2.])

array([1., 2., 2., 2., 2.], dtype=float32)

In [12]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
a
b

array([2., 2., 2., 2., 2.])

array([2., 2., 2., 2., 2.])

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [14]:
if torch.cuda.is_available():
    x=x.cuda()
    y=y.cuda()
    x+y
torch.cuda.is_available()

False